### ISSUE TITLE
Switch to permissive license

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [JuliaGeometry/TetGen.jl#29]
This project currently uses the [GNU Affero GPL v3 license](https://opensource.org/licenses/AGPL-3.0). I set this license because TetGen carries this license and it is assumed that the "copy left" license means TetGen.jl should carry the same license. However, I believe (correct me if I'm wrong) this "midas touch" effect would only kick in uppon distribution of TetGen's source with TetGen.jl. Therefore it seems to be that if we do not ship any TetGen codes, but instead ask users to download TetGen themselves, that we are again free to choose whatever license we want. In that case a permissive license, like the MIT or Apache 2.0 license, could be preferred. 

@SimonDanisch is the above possible/preferred? Currently any project featuring TetGen.jl would also need to use the GNU Affero GPL v3 license (the midas touch continues), which some find a deterrent.

**Comment by SimonDanisch** [comment]
So I think we can definitely license the wrapper as MIT and I think that's what the license is about here.
BinaryBuilder just correctly install the Tetgen license when installing it.
I'm not 100% sure what that means concretely for the package, though ..

**Comment by j-fu** [comment]
Hi, this will be an interesting discussion. 
Disclaimer first: I am significantly involved in development of the TetGen licensing scheme, and in short, the switch to AGPL historically was the only way to  start distributing under a proper OSI approved license. One point here is that we (as a research institute) are able to generate funding via dual licensing. 

Technically, TetGen.jl depends on TetGen_jll.jl which as been developed from the C wrapper code (MIT licensed) of @SimonDanisch and conveys the TetGen source via link to a github repo containing the source (another issue here - I am currently trying to organize a proper upstream repo).

A couple of points for start:

- Is installation of the jll via Pkg (which always happens on the computer of the user and is initiated by the user) equivalent to "downloading TetGen themselves"  ? (could be...)
- Due to the interaction via ccall, Julia source code and TetGen source code never get into direct touch.  
- PackageCompiler generated binaries IMHO are "covered work". (I did not try them out yet - how do the include jll objects?).
- I see significant maintenance costs with going back to "pre-jll" times  - essentially this would prevent the use of the code  by non-power users.  
- See https://github.com/j-fu/SimplexGridFactory.jl for another workaround option (which I developed, so I believe it its correct :) )
- Has the SuitepSparse/GPL issue already been resolved for Julia proper ?

**Comment by SimonDanisch** [comment]
Ha, didn't know that... I guess that takes away some of the guess work :D 

The more I think about it, the more I think we should go with a similar solution that BinaryProvider uses for their OSX sandbox: 
You need to set an env var to force a user interaction when downloading TetGen_jll, to notify anyone who depends in anway on the TetGen code, that they're now using AGPL licensed code.
I think that should fix the "make people aware that they now need to respect AGPL", when using any dependency of `TetGen_jll`, which seems to be the main concern to be respected?

**Comment by j-fu** [comment]
... found this related general discussion: https://discourse.julialang.org/t/licensing-julia-wrappers/38973
I doubt that an environment variable based hook is possible with jll download  as this process just seems to be based on Pkg.  
No final conclusion yet, though.

**Comment by j-fu** [comment]
In fact we have a precedent with FFTW.jl : it (optionally) uses the GPLed fftw lib,  but itself it is MIT licensed.
The GPL situation is stated in the README. In fact I think we might use a similar scheme. I tend to see users to have an active responsibility  regarding license compliance, that means that they are responsible to do the corresponding research on license terms. To ease their job, any package which potentially uses TetGen should provide the information about TetGen's licensing. 
I tend to agree with Stefan Karpinsky here: https://discourse.julialang.org/t/gpl-and-virality/7715

The aforementioned dual licensing scheme essentially shall give us a share from the profit someone wants to make profit from closed source distribution  of his covered work.  Scientific profit comes from citatations.

**Comment by vchuravy** [comment]
The precedent FFTW sets is the correct one to rely upon. It also uses a JLLWrapper to download the library https://github.com/JuliaMath/FFTW.jl/blob/5f6f3155825a2bd5b470546a082deb3df366de19/Project.toml#L7

Artifacts created with PkgCompiler will contain the GPL licensed binaries and if one wants to distribute those, the terms of the GPL applies.

**Comment by j-fu** [comment]
See #30

**Comment by j-fu** [comment]
Seems there are no objections  ? Would merge the PR then tomorrow.

**Comment by j-fu** [comment]
Ok merged #30
